version: '3.5' 

services:
    redis:
      image: redis
      restart: unless-stopped
      ports: 
        - 6379:6379
      container_name: redis

    example-backend:  
      build: ./example-backend
      environment: 
        - REDIS_HOST=redis
      ports: 
        - 8080:8080
      container_name: example-backend

    example-frontend:  
      build: ./example-frontend
      ports: 
        - 5000:5000
      container_name: example-frontend