FROM ubuntu:18.04

WORKDIR /usr/src/app

RUN apt update
RUN apt install -y curl

RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -

RUN apt install -y nodejs

COPY . .

RUN npm install


#RUN REACT_APP_BACKEND_URL=http://localhost/api/ npm run build
RUN npm run build

RUN npm install -g serve

RUN useradd -m appuser
RUN chown appuser /usr/src/app
USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]