FROM node:16-alpine

WORKDIR /usr/src/app

COPY . .

RUN adduser -D appuser && \
    chown appuser /usr/src/app && \
    npm install && \
    npm run build && \
    npm install -g serve

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]