FROM node:16-alpine as build-stage

WORKDIR /usr/src/app

COPY . .

RUN npm install && \
    npm run build

USER appuser

FROM node:16-alpine

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/build /usr/src/app/build

RUN adduser -D appuser && \
    chown appuser /usr/src/app && \
    npm install -g serve

CMD ["serve", "-s", "-l", "5000", "build"]