FROM ubuntu:18.04

WORKDIR /usr/src/app

COPY . .

RUN apt update && \
    apt install -y curl && \
    curl -sL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt install -y nodejs && \
    npm install && \
    npm run build && \
    npm install -g serve && \
    apt-get purge -y --auto-remove curl && \ 
    rm -rf /var/lib/apt/lists/* && \
    useradd -m appuser && \
    chown appuser /usr/src/app

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]